HepMC::IO_BaseClass Class Reference
all input/output classes inherit from IO_BaseClass
#include <IO_BaseClass.h>
Public Member Functions
virtual ~IO_BaseClass ()
virtual void write_event (const GenEvent *)=0
write this GenEvent
virtual bool fill_next_event (GenEvent *)=0
fill this GenEvent
virtual void write_particle_data_table (const ParticleDataTable *)=0
write this ParticleDataTable
virtual bool fill_particle_data_table (ParticleDataTable *)=0
fill this ParticleDataTable
virtual void print (std::ostream &ostr=std::cout) const
write output to ostr
GenEvent * read_next_event ()
do not over-ride
ParticleDataTable * read_particle_data_table ()
do not over-ride
virtual GenEvent *& operator>> (GenEvent *&)
the same as read_next_event
virtual const GenEvent *& operator<< (const GenEvent *&)
the same as write_event
virtual GenEvent *& operator<< (GenEvent *&)
the same as write_event
virtual ParticleDataTable *& operator>> (ParticleDataTable *&)
the same as read_particle_data_table
virtual const ParticleDataTable *& operator<< (const ParticleDataTable *&)
the same as write_particle_data_table
virtual ParticleDataTable *& operator<< (ParticleDataTable *&)
the same as write_particle_data_table
Detailed Description
all input/output classes inherit from IO_BaseClass
If you want to write a new IO class, then inherit from this class and re-define read_event() and write_event()
Definition at line 35 of file IO_BaseClass.h.
Constructor & Destructor Documentation
virtual HepMC::IO_BaseClass::~IO_BaseClass () [inline, virtual]
Definition at line 37 of file IO_BaseClass.h.
Member Function Documentation
virtual void HepMC::IO_BaseClass::write_event (const GenEvent *) [pure virtual]
write this GenEvent
Implemented in HepMC::IO_Ascii , HepMC::IO_AsciiParticles , HepMC::IO_ExtendedAscii , and HepMC::IO_HEPEVT .
Referenced by operator<<().
virtual bool HepMC::IO_BaseClass::fill_next_event (GenEvent *) [pure virtual]
fill this GenEvent
Implemented in HepMC::IO_Ascii , HepMC::IO_AsciiParticles , HepMC::IO_ExtendedAscii , HepMC::IO_HEPEVT , and HepMC::IO_HERWIG .
Referenced by read_next_event().
virtual void HepMC::IO_BaseClass::write_particle_data_table (const ParticleDataTable *) [pure virtual]
write this ParticleDataTable
Implemented in HepMC::IO_Ascii , HepMC::IO_AsciiParticles , and HepMC::IO_ExtendedAscii .
Referenced by operator<<().
virtual bool HepMC::IO_BaseClass::fill_particle_data_table (ParticleDataTable *) [pure virtual]
fill this ParticleDataTable
Implemented in HepMC::IO_Ascii , HepMC::IO_AsciiParticles , HepMC::IO_ExtendedAscii , and HepMC::IO_PDG_ParticleDataTable .
Referenced by read_particle_data_table().
void HepMC::IO_BaseClass::print (std::ostream & ostr = std::cout) const [inline, virtual]
write output to ostr
Reimplemented in HepMC::IO_Ascii , HepMC::IO_AsciiParticles , HepMC::IO_ExtendedAscii , HepMC::IO_HEPEVT , HepMC::IO_HERWIG , and HepMC::IO_PDG_ParticleDataTable .
Definition at line 117 of file IO_BaseClass.h.
GenEvent * HepMC::IO_BaseClass::read_next_event () [inline]
do not over-ride
creates a new event and fills it by calling the sister method read_next_event(GenEvent*)
Examples:
example_MyHerwig.cc, example_MyPythia.cc, example_MyPythiaOnlyToHepMC.cc, example_MyPythiaRead.cc, example_MyPythiaWithEventSelection.cc, and example_PythiaParticle.cc.
Definition at line 87 of file IO_BaseClass.h.
References fill_next_event().
Referenced by main(), and operator>>().
ParticleDataTable * HepMC::IO_BaseClass::read_particle_data_table () [inline]
do not over-ride
creates a new particle data table and fills it by calling the sister method read_particle_data_table(ParticleDataTable*)
Definition at line 103 of file IO_BaseClass.h.
References fill_particle_data_table().
Referenced by main(), and operator>>().
GenEvent *& HepMC::IO_BaseClass::operator>> (GenEvent *&) [inline, virtual]
the same as read_next_event
Definition at line 121 of file IO_BaseClass.h.
References read_next_event().
const GenEvent *& HepMC::IO_BaseClass::operator<< (const GenEvent *&) [inline, virtual]
the same as write_event
Definition at line 126 of file IO_BaseClass.h.
References write_event().
GenEvent *& HepMC::IO_BaseClass::operator<< (GenEvent *&) [inline, virtual]
the same as write_event
Definition at line 132 of file IO_BaseClass.h.
References write_event().
ParticleDataTable *& HepMC::IO_BaseClass::operator>> (ParticleDataTable *&) [inline, virtual]
the same as read_particle_data_table
Definition at line 137 of file IO_BaseClass.h.
References read_particle_data_table().
const ParticleDataTable *& HepMC::IO_BaseClass::operator<< (const ParticleDataTable *&) [inline, virtual]
the same as write_particle_data_table
Definition at line 143 of file IO_BaseClass.h.
References write_particle_data_table().
ParticleDataTable *& HepMC::IO_BaseClass::operator<< (ParticleDataTable *&) [inline, virtual]
the same as write_particle_data_table
Definition at line 149 of file IO_BaseClass.h.
References write_particle_data_table().
The documentation for this class was generated from the following file:
IO_BaseClass.h