HepMC::PdfInfo Class Reference
The PdfInfo class stores PDF information.
#include <PdfInfo.h>
Public Member Functions
PdfInfo ()
default constructor
PdfInfo (int i1, int i2, double x1, double x2, double q, double p1, double p2)
all values must be provided
~PdfInfo ()
PdfInfo (PdfInfo const &orig)
copy constructor
PdfInfo & operator= (PdfInfo const &rhs)
make a copy
void swap (PdfInfo &other)
swap two PdfInfo objects
bool operator== (const PdfInfo &) const
check for equality
bool operator!= (const PdfInfo &) const
check for inequality
int id1 () const
flavour code of first parton
int id2 () const
flavour code of second parton
double x1 () const
fraction of beam momentum carried by first parton (`beam side`)
double x2 () const
fraction of beam momentum carried by second parton (`target side`)
double scalePDF () const
Q-scale used in evaluation of PDF's (in GeV).
double pdf1 () const
PDF (id1, x1, Q).
double pdf2 () const
PDF (id2, x2, Q).
void set_id1 (const int &i)
set flavour code of first parton
void set_id2 (const int &i)
set flavour code of second parton
void set_x1 (const double &f)
set fraction of beam momentum carried by first parton (`beam side`)
void set_x2 (const double &f)
set fraction of beam momentum carried by second parton (`target side`)
void set_scalePDF (const double &f)
set Q-scale used in evaluation of PDF's (in GeV)
void set_pdf1 (const double &f)
set PDF (id1, x1, Q)
void set_pdf2 (const double &f)
set PDF (id2, x2, Q)
Detailed Description
The PdfInfo class stores PDF information.
HepMC::PdfInfo stores additional PDF information for a GenEvent. Creation and use of this information is optional.
Definition at line 30 of file PdfInfo.h.
Constructor & Destructor Documentation
HepMC::PdfInfo::PdfInfo () [inline]
default constructor
Definition at line 36 of file PdfInfo.h.
HepMC::PdfInfo::PdfInfo (int i1, int i2, double x1, double x2, double q, double p1, double p2) [inline]
all values must be provided
Definition at line 106 of file PdfInfo.h.
HepMC::PdfInfo::~PdfInfo () [inline]
Definition at line 49 of file PdfInfo.h.
HepMC::PdfInfo::PdfInfo (PdfInfo const & orig) [inline]
copy constructor
Definition at line 116 of file PdfInfo.h.
Member Function Documentation
PdfInfo & HepMC::PdfInfo::operator= (PdfInfo const & rhs) [inline]
make a copy
Definition at line 126 of file PdfInfo.h.
References swap().
void HepMC::PdfInfo::swap (PdfInfo & other) [inline]
swap two PdfInfo objects
Definition at line 133 of file PdfInfo.h.
References m_id1, m_id2, m_pdf1, m_pdf2, m_scalePDF, m_x1, and m_x2.
Referenced by operator=().
bool HepMC::PdfInfo::operator== (const PdfInfo &) const [inline]
check for equality
equality requires that each member match
Definition at line 144 of file PdfInfo.h.
References id1(), id2(), pdf1(), pdf2(), scalePDF(), x1(), and x2().
bool HepMC::PdfInfo::operator!= (const PdfInfo &) const [inline]
check for inequality
any nonmatching member generates inequality
Definition at line 156 of file PdfInfo.h.
int HepMC::PdfInfo::id1 () const [inline]
flavour code of first parton
Definition at line 64 of file PdfInfo.h.
Referenced by operator==(), and HepMC::IO_ExtendedAscii::write_pdf_info().
int HepMC::PdfInfo::id2 () const [inline]
flavour code of second parton
Definition at line 66 of file PdfInfo.h.
Referenced by operator==(), and HepMC::IO_ExtendedAscii::write_pdf_info().
double HepMC::PdfInfo::x1 () const [inline]
fraction of beam momentum carried by first parton (`beam side`)
Definition at line 68 of file PdfInfo.h.
Referenced by operator==(), and HepMC::IO_ExtendedAscii::write_pdf_info().
double HepMC::PdfInfo::x2 () const [inline]
fraction of beam momentum carried by second parton (`target side`)
Definition at line 70 of file PdfInfo.h.
Referenced by operator==(), and HepMC::IO_ExtendedAscii::write_pdf_info().
double HepMC::PdfInfo::scalePDF () const [inline]
Q-scale used in evaluation of PDF's (in GeV).
Definition at line 72 of file PdfInfo.h.
Referenced by operator==(), and HepMC::IO_ExtendedAscii::write_pdf_info().
double HepMC::PdfInfo::pdf1 () const [inline]
PDF (id1, x1, Q).
Definition at line 74 of file PdfInfo.h.
Referenced by operator==(), and HepMC::IO_ExtendedAscii::write_pdf_info().
double HepMC::PdfInfo::pdf2 () const [inline]
PDF (id2, x2, Q).
Definition at line 76 of file PdfInfo.h.
Referenced by operator==(), and HepMC::IO_ExtendedAscii::write_pdf_info().
void HepMC::PdfInfo::set_id1 (const int & i) [inline]
set flavour code of first parton
Definition at line 80 of file PdfInfo.h.
void HepMC::PdfInfo::set_id2 (const int & i) [inline]
set flavour code of second parton
Definition at line 82 of file PdfInfo.h.
void HepMC::PdfInfo::set_x1 (const double & f) [inline]
set fraction of beam momentum carried by first parton (`beam side`)
Definition at line 84 of file PdfInfo.h.
void HepMC::PdfInfo::set_x2 (const double & f) [inline]
set fraction of beam momentum carried by second parton (`target side`)
Definition at line 86 of file PdfInfo.h.
void HepMC::PdfInfo::set_scalePDF (const double & f) [inline]
set Q-scale used in evaluation of PDF's (in GeV)
Definition at line 88 of file PdfInfo.h.
void HepMC::PdfInfo::set_pdf1 (const double & f) [inline]
set PDF (id1, x1, Q)
Definition at line 90 of file PdfInfo.h.
void HepMC::PdfInfo::set_pdf2 (const double & f) [inline]
set PDF (id2, x2, Q)
Definition at line 92 of file PdfInfo.h.
The documentation for this class was generated from the following file:
PdfInfo.h