IsGoodEvent Class Reference
example class
#include <IsGoodEvent.h>
Public Member Functions
bool operator() (const HepMC::GenEvent *evt)
check this event for goodness
bool operator() (const HepMC::GenEvent *evt)
Detailed Description
example class
event selection predicate. returns true if the event contains a photon with pT > 50 GeV
Examples:
example_EventSelection.cc.
Definition at line 20 of file example_EventSelection.cc.
Member Function Documentation
bool IsGoodEvent::operator() (const HepMC::GenEvent * evt) [inline]
check this event for goodness
Examples:
example_EventSelection.cc.
Definition at line 23 of file example_EventSelection.cc.
References p, HepMC::GenEvent::particles_begin(), and HepMC::GenEvent::particles_end().
bool IsGoodEvent::operator() (const HepMC::GenEvent * evt) [inline]
Definition at line 14 of file IsGoodEvent.h.
References p, HepMC::GenEvent::particles_begin(), and HepMC::GenEvent::particles_end().
The documentation for this class was generated from the following files:
example_EventSelection.cc
IsGoodEvent.h