HepMC::IO_ExtendedAscii Class Reference
IO_ExtendedAscii also deals with HeavyIon and PdfInfo.
#include <IO_ExtendedAscii.h>
Public Member Functions
IO_ExtendedAscii (const char *filename=`IO_ExtendedAscii.dat`, std::ios::openmode mode=std::ios::out)
constructor requiring a file name and std::ios mode
virtual ~IO_ExtendedAscii ()
void write_event (const GenEvent *evt)
write this event
bool fill_next_event (GenEvent *evt)
get the next event
void write_particle_data_table (const ParticleDataTable *)
write this ParticleDataTable
bool fill_particle_data_table (ParticleDataTable *)
fill this ParticleDataTable
void write_comment (const std::string comment)
int rdstate () const
check the state of the IO stream
void clear ()
clear the IO stream
void print (std::ostream &ostr=std::cout) const
write to ostr
Protected Member Functions
void write_vertex (GenVertex *)
write vertex information
void write_beam_particles (std::pair< HepMC::GenParticle *, HepMC::GenParticle * >)
write beam particle information
void write_heavy_ion (HeavyIon *)
write heavy ion information
void write_pdf_info (PdfInfo *)
write PDF information
void write_particle (GenParticle *p)
write particle information
void write_particle_data (const ParticleData *d)
write particle data information
GenVertex * read_vertex (TempParticleMap &particle_to_end_vertex)
read vertex information
GenParticle * read_particle (TempParticleMap &particle_to_end_vertex)
read GenParticle information
ParticleData * read_particle_data (ParticleDataTable *)
read particle data table information
HeavyIon * read_heavy_ion ()
read heavy ion information
PdfInfo * read_pdf_info ()
read PDF information
bool write_end_listing ()
write end tag
bool search_for_key_end (std::istream &in, const char *key)
look for line type (key)
bool search_for_key_beginning (std::istream &in, const char *key)
look for line type (key)
bool eat_key (std::iostream &in, const char *key)
string manipulation accounting
int find_in_map (const std::map< HepMC::GenVertex *, int > &m, GenVertex *v) const
find this vertex in the map of vertices
void output (const double &)
write double
void output (const float &)
write float
void output (const int &)
write int
void output (const long int &)
write long int
void output (const char &)
write a single character
Detailed Description
IO_ExtendedAscii also deals with HeavyIon and PdfInfo.
event input/output in ascii format for machine reading extended format contains HeavyIon and PdfInfo classes
Examples:
example_MyPythia.cc.
Definition at line 64 of file IO_ExtendedAscii.h.
Constructor & Destructor Documentation
HepMC::IO_ExtendedAscii::IO_ExtendedAscii (const char * filename = `IO_ExtendedAscii.dat`, std::ios::openmode mode = std::ios::out)
constructor requiring a file name and std::ios mode
Definition at line 18 of file IO_ExtendedAscii.cc.
HepMC::IO_ExtendedAscii::~IO_ExtendedAscii () [virtual]
Definition at line 37 of file IO_ExtendedAscii.cc.
References write_end_listing().
Member Function Documentation
void HepMC::IO_ExtendedAscii::write_event (const GenEvent * evt) [virtual]
write this event
Writes evt to m_file. It does NOT delete the event after writing.
Implements HepMC::IO_BaseClass .
Definition at line 52 of file IO_ExtendedAscii.cc.
References HepMC::GenEvent::alphaQCD(), HepMC::GenEvent::alphaQED(), HepMC::GenVertex::barcode(), HepMC::GenEvent::beam_particles(), HepMC::WeightContainer::begin(), HepMC::WeightContainer::end(), HepMC::GenEvent::event_number(), HepMC::GenEvent::event_scale(), HepMC::GenEvent::heavy_ion(), HepMC::GenEvent::mpi(), output(), HepMC::GenEvent::pdf_info(), HepMC::GenEvent::random_states(), HepMC::GenEvent::signal_process_id(), HepMC::GenEvent::signal_process_vertex(), HepMC::WeightContainer::size(), v, HepMC::versionName(), HepMC::GenEvent::vertices_begin(), HepMC::GenEvent::vertices_end(), HepMC::GenEvent::vertices_size(), HepMC::GenEvent::weights(), write_beam_particles(), write_heavy_ion(), write_pdf_info(), and write_vertex().
bool HepMC::IO_ExtendedAscii::fill_next_event (GenEvent * evt) [virtual]
get the next event
Implements HepMC::IO_BaseClass .
Definition at line 105 of file IO_ExtendedAscii.cc.
References HepMC::GenVertex::add_particle_in(), HepMC::GenEvent::add_vertex(), HepMC::GenEvent::barcode_to_vertex(), eat_key(), HepMC::TempParticleMap::end_vertex(), HepMC::TempParticleMap::order_begin(), HepMC::TempParticleMap::order_end(), p, read_heavy_ion(), read_pdf_info(), read_vertex(), search_for_key_end(), HepMC::GenEvent::set_beam_particles(), HepMC::GenEvent::set_event_number(), HepMC::GenEvent::set_heavy_ion(), HepMC::GenEvent::set_mpi(), HepMC::GenEvent::set_pdf_info(), HepMC::GenEvent::set_random_states(), HepMC::GenEvent::set_signal_process_id(), HepMC::GenEvent::set_signal_process_vertex(), v, and HepMC::GenEvent::weights().
void HepMC::IO_ExtendedAscii::write_particle_data_table (const ParticleDataTable *) [virtual]
write this ParticleDataTable
Implements HepMC::IO_BaseClass .
Definition at line 239 of file IO_ExtendedAscii.cc.
References HepMC::ParticleDataTable::begin(), HepMC::ParticleDataTable::end(), write_end_listing(), and write_particle_data().
bool HepMC::IO_ExtendedAscii::fill_particle_data_table (ParticleDataTable *) [virtual]
fill this ParticleDataTable
Implements HepMC::IO_BaseClass .
Definition at line 259 of file IO_ExtendedAscii.cc.
References eat_key(), read_particle_data(), search_for_key_end(), and HepMC::ParticleDataTable::set_description().
void HepMC::IO_ExtendedAscii::write_comment (const std::string comment)
insert a comment directly into the output file --- normally you only want to do this at the beginning or end of the file. All comments are preceded with `HepMC::IO_ExtendedAscii-COMMENT\n`
Definition at line 224 of file IO_ExtendedAscii.cc.
References write_end_listing().
int HepMC::IO_ExtendedAscii::rdstate () const [inline]
check the state of the IO stream
Definition at line 159 of file IO_ExtendedAscii.h.
void HepMC::IO_ExtendedAscii::clear () [inline]
clear the IO stream
Definition at line 160 of file IO_ExtendedAscii.h.
void HepMC::IO_ExtendedAscii::print (std::ostream & ostr = std::cout) const [virtual]
write to ostr
Reimplemented from HepMC::IO_BaseClass .
Definition at line 42 of file IO_ExtendedAscii.cc.
void HepMC::IO_ExtendedAscii::write_vertex (GenVertex *) [protected]
write vertex information
Definition at line 307 of file IO_ExtendedAscii.cc.
References output(), v, and write_particle().
Referenced by write_event().
void HepMC::IO_ExtendedAscii::write_beam_particles (std::pair< HepMC::GenParticle *, HepMC::GenParticle * >) [protected]
write beam particle information
Referenced by write_event().
void HepMC::IO_ExtendedAscii::write_heavy_ion (HeavyIon *) [protected]
write heavy ion information
Definition at line 370 of file IO_ExtendedAscii.cc.
References HepMC::HeavyIon::eccentricity(), HepMC::HeavyIon::event_plane_angle(), HepMC::HeavyIon::impact_parameter(), HepMC::HeavyIon::N_Nwounded_collisions(), HepMC::HeavyIon::Ncoll(), HepMC::HeavyIon::Ncoll_hard(), HepMC::HeavyIon::Npart_proj(), HepMC::HeavyIon::Npart_targ(), HepMC::HeavyIon::Nwounded_N_collisions(), HepMC::HeavyIon::Nwounded_Nwounded_collisions(), output(), HepMC::HeavyIon::sigma_inel_NN(), HepMC::HeavyIon::spectator_neutrons(), and HepMC::HeavyIon::spectator_protons().
Referenced by write_event().
void HepMC::IO_ExtendedAscii::write_pdf_info (PdfInfo *) [protected]
write PDF information
Definition at line 414 of file IO_ExtendedAscii.cc.
References HepMC::PdfInfo::id1(), HepMC::PdfInfo::id2(), output(), HepMC::PdfInfo::pdf1(), HepMC::PdfInfo::pdf2(), HepMC::PdfInfo::scalePDF(), HepMC::PdfInfo::x1(), and HepMC::PdfInfo::x2().
Referenced by write_event().
void HepMC::IO_ExtendedAscii::write_particle (GenParticle * p) [protected]
write particle information
Definition at line 446 of file IO_ExtendedAscii.cc.
References output(), and p.
Referenced by write_vertex().
void HepMC::IO_ExtendedAscii::write_particle_data (const ParticleData * d) [protected]
write particle data information
Definition at line 471 of file IO_ExtendedAscii.cc.
References HepMC::ParticleData::charge(), HepMC::ParticleData::clifetime(), HepMC::ParticleData::mass(), HepMC::ParticleData::name(), output(), HepMC::ParticleData::pdg_id(), and HepMC::ParticleData::spin().
Referenced by write_particle_data_table().
GenVertex * HepMC::IO_ExtendedAscii::read_vertex (TempParticleMap & particle_to_end_vertex) [protected]
read vertex information
Definition at line 490 of file IO_ExtendedAscii.cc.
References read_particle(), and v.
Referenced by fill_next_event().
GenParticle * HepMC::IO_ExtendedAscii::read_particle (TempParticleMap & particle_to_end_vertex) [protected]
read GenParticle information
Definition at line 575 of file IO_ExtendedAscii.cc.
References HepMC::TempParticleMap::addEndParticle(), p, and HepMC::Flow::set_icode().
Referenced by read_vertex().
ParticleData * HepMC::IO_ExtendedAscii::read_particle_data (ParticleDataTable *) [protected]
read particle data table information
Definition at line 617 of file IO_ExtendedAscii.cc.
References HepMC::ParticleDataTable::insert().
Referenced by fill_particle_data_table().
HeavyIon * HepMC::IO_ExtendedAscii::read_heavy_ion () [protected]
read heavy ion information
Definition at line 526 of file IO_ExtendedAscii.cc.
Referenced by fill_next_event().
PdfInfo * HepMC::IO_ExtendedAscii::read_pdf_info () [protected]
read PDF information
Definition at line 552 of file IO_ExtendedAscii.cc.
Referenced by fill_next_event().
bool HepMC::IO_ExtendedAscii::write_end_listing () [protected]
write end tag
Definition at line 639 of file IO_ExtendedAscii.cc.
Referenced by write_comment(), write_particle_data_table(), and ~IO_ExtendedAscii().
bool HepMC::IO_ExtendedAscii::search_for_key_end (std::istream & in, const char * key) [protected]
look for line type (key)
reads characters from in until the string of characters matching key is found (success) or EOF is reached (failure). It stops immediately thereafter. Returns T/F for success/fail
Definition at line 648 of file IO_ExtendedAscii.cc.
Referenced by fill_next_event(), fill_particle_data_table(), and search_for_key_beginning().
bool HepMC::IO_ExtendedAscii::search_for_key_beginning (std::istream & in, const char * key) [protected]
look for line type (key)
not tested and NOT used anywhere!
Definition at line 664 of file IO_ExtendedAscii.cc.
References search_for_key_end().
bool HepMC::IO_ExtendedAscii::eat_key (std::iostream & in, const char * key) [protected]
string manipulation accounting
eats the character string key from istream in - only if the key is the very next occurence in the stream if the key is not the next occurence, it eats nothing ... i.e. it puts back whatever it would have eaten.
Definition at line 678 of file IO_ExtendedAscii.cc.
Referenced by fill_next_event(), and fill_particle_data_table().
int HepMC::IO_ExtendedAscii::find_in_map (const std::map< HepMC::GenVertex *, int > & m, GenVertex * v) const [protected]
find this vertex in the map of vertices
void HepMC::IO_ExtendedAscii::output (const double &) [inline, protected]
write double
Definition at line 142 of file IO_ExtendedAscii.h.
Referenced by write_event(), write_heavy_ion(), write_particle(), write_particle_data(), write_pdf_info(), and write_vertex().
void HepMC::IO_ExtendedAscii::output (const float &) [inline, protected]
write float
Definition at line 149 of file IO_ExtendedAscii.h.
void HepMC::IO_ExtendedAscii::output (const int &) [inline, protected]
write int
Definition at line 156 of file IO_ExtendedAscii.h.
void HepMC::IO_ExtendedAscii::output (const long int &) [inline, protected]
write long int
Definition at line 157 of file IO_ExtendedAscii.h.
void HepMC::IO_ExtendedAscii::output (const char &) [inline, protected]
write a single character
Definition at line 158 of file IO_ExtendedAscii.h.
The documentation for this class was generated from the following files:
IO_ExtendedAscii.h
IO_ExtendedAscii.cc