HepMC::HeavyIon Class Reference
The HeavyIon class stores information about heavy ions.
#include <HeavyIon.h>
Public Member Functions
HeavyIon ()
default constructor
HeavyIon (int nh, int np, int nt, int nc, int ns, int nsp, int nnw=0, int nwn=0, int nwnw=0, float im=0., float pl=0., float ec=0., float s=0.)
The first 6 values must be provided.
~HeavyIon ()
HeavyIon (HeavyIon const &orig)
copy constructor
HeavyIon & operator= (HeavyIon const &rhs)
make a copy
void swap (HeavyIon &other)
swap two HeavyIon objects
bool operator== (const HeavyIon &) const
check for equality
bool operator!= (const HeavyIon &) const
check for inequality
int Ncoll_hard () const
Number of hard scatterings.
int Npart_proj () const
Number of projectile participants.
int Npart_targ () const
Number of target participants.
int Ncoll () const
Number of NN (nucleon-nucleon) collisions.
int spectator_neutrons () const
Number of spectator neutrons.
int spectator_protons () const
Number of spectator protons.
int N_Nwounded_collisions () const
Number of N-Nwounded collisions.
int Nwounded_N_collisions () const
Number of Nwounded-N collisons.
int Nwounded_Nwounded_collisions () const
Number of Nwounded-Nwounded collisions.
float impact_parameter () const
Impact Parameter(in fm) of collision.
float event_plane_angle () const
Azimuthal angle of event plane.
float eccentricity () const
float sigma_inel_NN () const
nucleon-nucleon inelastic (including diffractive) cross-section
void set_Ncoll_hard (const int &i)
set number of hard scatterings
void set_Npart_proj (const int &i)
set number of projectile participants
void set_Npart_targ (const int &i)
set number of target participants
void set_Ncoll (const int &i)
set number of NN (nucleon-nucleon) collisions
void set_spectator_neutrons (const int &i)
set number of spectator neutrons
void set_spectator_protons (const int &i)
set number of spectator protons
void set_N_Nwounded_collisions (const int &i)
set number of N-Nwounded collisions
void set_Nwounded_N_collisions (const int &i)
set number of Nwounded-N collisons
void set_Nwounded_Nwounded_collisions (const int &i)
set number of Nwounded-Nwounded collisions
void set_impact_parameter (const float &f)
set Impact Parameter in fm
void set_event_plane_angle (const float &f)
set azimuthal angle of event plane
void set_eccentricity (const float &f)
set eccentricity of participating nucleons in the transverse plane
void set_sigma_inel_NN (const float &f)
set nucleon-nucleon inelastic cross-section
Detailed Description
The HeavyIon class stores information about heavy ions.
HepMC::HeavyIon provides additional information storage for Heavy Ion generators in GenEvent. Creation and use of this information is optional.
Definition at line 45 of file HeavyIon.h.
Constructor & Destructor Documentation
HepMC::HeavyIon::HeavyIon () [inline]
default constructor
Definition at line 51 of file HeavyIon.h.
HepMC::HeavyIon::HeavyIon (int nh, int np, int nt, int nc, int ns, int nsp, int nnw = 0, int nwn = 0, int nwnw = 0, float im = 0., float pl = 0., float ec = 0., float s = 0.) [inline]
The first 6 values must be provided.
Required members are the number of hard scatterings, the number of projectile participants. the number of target participants. the number of nucleon-nucleon collisions, the number of spectator neutrons, and the number of spectator protons.
Definition at line 168 of file HeavyIon.h.
HepMC::HeavyIon::~HeavyIon () [inline]
Definition at line 72 of file HeavyIon.h.
HepMC::HeavyIon::HeavyIon (HeavyIon const & orig) [inline]
copy constructor
Definition at line 186 of file HeavyIon.h.
Member Function Documentation
HeavyIon & HepMC::HeavyIon::operator= (HeavyIon const & rhs) [inline]
make a copy
Definition at line 202 of file HeavyIon.h.
References swap().
void HepMC::HeavyIon::swap (HeavyIon & other) [inline]
swap two HeavyIon objects
Definition at line 209 of file HeavyIon.h.
References m_eccentricity, m_event_plane_angle, m_impact_parameter, m_N_Nwounded_collisions, m_Ncoll, m_Ncoll_hard, m_Npart_proj, m_Npart_targ, m_Nwounded_N_collisions, m_Nwounded_Nwounded_collisions, m_sigma_inel_NN, m_spectator_neutrons, and m_spectator_protons.
Referenced by operator=().
bool HepMC::HeavyIon::operator== (const HeavyIon &) const [inline]
check for equality
equality requires that each member match
Definition at line 226 of file HeavyIon.h.
References eccentricity(), event_plane_angle(), impact_parameter(), N_Nwounded_collisions(), Ncoll(), Ncoll_hard(), Npart_proj(), Npart_targ(), Nwounded_N_collisions(), Nwounded_Nwounded_collisions(), sigma_inel_NN(), spectator_neutrons(), and spectator_protons().
bool HepMC::HeavyIon::operator!= (const HeavyIon &) const [inline]
check for inequality
any nonmatching member generates inequality
Definition at line 244 of file HeavyIon.h.
int HepMC::HeavyIon::Ncoll_hard () const [inline]
Number of hard scatterings.
Definition at line 87 of file HeavyIon.h.
Referenced by operator==(), and HepMC::IO_ExtendedAscii::write_heavy_ion().
int HepMC::HeavyIon::Npart_proj () const [inline]
Number of projectile participants.
Definition at line 89 of file HeavyIon.h.
Referenced by operator==(), and HepMC::IO_ExtendedAscii::write_heavy_ion().
int HepMC::HeavyIon::Npart_targ () const [inline]
Number of target participants.
Definition at line 91 of file HeavyIon.h.
Referenced by operator==(), and HepMC::IO_ExtendedAscii::write_heavy_ion().
int HepMC::HeavyIon::Ncoll () const [inline]
Number of NN (nucleon-nucleon) collisions.
Definition at line 93 of file HeavyIon.h.
Referenced by operator==(), and HepMC::IO_ExtendedAscii::write_heavy_ion().
int HepMC::HeavyIon::spectator_neutrons () const [inline]
Number of spectator neutrons.
Definition at line 95 of file HeavyIon.h.
Referenced by operator==(), and HepMC::IO_ExtendedAscii::write_heavy_ion().
int HepMC::HeavyIon::spectator_protons () const [inline]
Number of spectator protons.
Definition at line 97 of file HeavyIon.h.
Referenced by operator==(), and HepMC::IO_ExtendedAscii::write_heavy_ion().
int HepMC::HeavyIon::N_Nwounded_collisions () const [inline]
Number of N-Nwounded collisions.
Definition at line 99 of file HeavyIon.h.
Referenced by operator==(), and HepMC::IO_ExtendedAscii::write_heavy_ion().
int HepMC::HeavyIon::Nwounded_N_collisions () const [inline]
Number of Nwounded-N collisons.
Definition at line 101 of file HeavyIon.h.
Referenced by operator==(), and HepMC::IO_ExtendedAscii::write_heavy_ion().
int HepMC::HeavyIon::Nwounded_Nwounded_collisions () const [inline]
Number of Nwounded-Nwounded collisions.
Definition at line 103 of file HeavyIon.h.
Referenced by operator==(), and HepMC::IO_ExtendedAscii::write_heavy_ion().
float HepMC::HeavyIon::impact_parameter () const [inline]
Impact Parameter(in fm) of collision.
Definition at line 105 of file HeavyIon.h.
Referenced by operator==(), and HepMC::IO_ExtendedAscii::write_heavy_ion().
float HepMC::HeavyIon::event_plane_angle () const [inline]
Azimuthal angle of event plane.
Definition at line 107 of file HeavyIon.h.
Referenced by operator==(), and HepMC::IO_ExtendedAscii::write_heavy_ion().
float HepMC::HeavyIon::eccentricity () const [inline]
eccentricity of participating nucleons in the transverse plane (as in phobos nucl-ex/0510031)
Definition at line 110 of file HeavyIon.h.
Referenced by operator==(), and HepMC::IO_ExtendedAscii::write_heavy_ion().
float HepMC::HeavyIon::sigma_inel_NN () const [inline]
nucleon-nucleon inelastic (including diffractive) cross-section
Definition at line 112 of file HeavyIon.h.
Referenced by operator==(), and HepMC::IO_ExtendedAscii::write_heavy_ion().
void HepMC::HeavyIon::set_Ncoll_hard (const int & i) [inline]
set number of hard scatterings
Definition at line 116 of file HeavyIon.h.
void HepMC::HeavyIon::set_Npart_proj (const int & i) [inline]
set number of projectile participants
Definition at line 118 of file HeavyIon.h.
void HepMC::HeavyIon::set_Npart_targ (const int & i) [inline]
set number of target participants
Definition at line 120 of file HeavyIon.h.
void HepMC::HeavyIon::set_Ncoll (const int & i) [inline]
set number of NN (nucleon-nucleon) collisions
Definition at line 122 of file HeavyIon.h.
void HepMC::HeavyIon::set_spectator_neutrons (const int & i) [inline]
set number of spectator neutrons
Definition at line 124 of file HeavyIon.h.
void HepMC::HeavyIon::set_spectator_protons (const int & i) [inline]
set number of spectator protons
Definition at line 126 of file HeavyIon.h.
void HepMC::HeavyIon::set_N_Nwounded_collisions (const int & i) [inline]
set number of N-Nwounded collisions
Definition at line 128 of file HeavyIon.h.
void HepMC::HeavyIon::set_Nwounded_N_collisions (const int & i) [inline]
set number of Nwounded-N collisons
Definition at line 130 of file HeavyIon.h.
void HepMC::HeavyIon::set_Nwounded_Nwounded_collisions (const int & i) [inline]
set number of Nwounded-Nwounded collisions
Definition at line 132 of file HeavyIon.h.
void HepMC::HeavyIon::set_impact_parameter (const float & f) [inline]
set Impact Parameter in fm
Definition at line 135 of file HeavyIon.h.
void HepMC::HeavyIon::set_event_plane_angle (const float & f) [inline]
set azimuthal angle of event plane
Definition at line 137 of file HeavyIon.h.
void HepMC::HeavyIon::set_eccentricity (const float & f) [inline]
set eccentricity of participating nucleons in the transverse plane
Definition at line 139 of file HeavyIon.h.
void HepMC::HeavyIon::set_sigma_inel_NN (const float & f) [inline]
set nucleon-nucleon inelastic cross-section
Definition at line 141 of file HeavyIon.h.
The documentation for this class was generated from the following file:
HeavyIon.h