HepMC::TempParticleMap Class Reference
TempParticleMap is a temporary GenParticle* container used during input.
#include <TempParticleMap.h>
Public Types
typedef std::map< HepMC::GenParticle *, int > TempMap
typedef std::map< int, HepMC::GenParticle * > TempOrderMap
typedef TempMap::iterator TempMapIterator
typedef TempOrderMap::iterator orderIterator
Public Member Functions
TempParticleMap ()
~TempParticleMap ()
TempMapIterator begin ()
TempMapIterator end ()
orderIterator order_begin ()
orderIterator order_end ()
int end_vertex (GenParticle *)
void addEndParticle (GenParticle *, int &)
Detailed Description
TempParticleMap is a temporary GenParticle* container used during input.
Used by IO classes for recoverable particle ordering. Map GenParticle* against both outgoing vertex and particle order.
Definition at line 24 of file TempParticleMap.h.
Member Typedef Documentation
typedef std::map<HepMC::GenParticle*,int> HepMC::TempParticleMap::TempMap
Definition at line 26 of file TempParticleMap.h.
typedef std::map<int,HepMC::GenParticle*> HepMC::TempParticleMap::TempOrderMap
Definition at line 27 of file TempParticleMap.h.
typedef TempMap::iterator HepMC::TempParticleMap::TempMapIterator
Definition at line 28 of file TempParticleMap.h.
typedef TempOrderMap::iterator HepMC::TempParticleMap::orderIterator
Definition at line 29 of file TempParticleMap.h.
Constructor & Destructor Documentation
HepMC::TempParticleMap::TempParticleMap () [inline]
Definition at line 31 of file TempParticleMap.h.
HepMC::TempParticleMap::~TempParticleMap () [inline]
Definition at line 34 of file TempParticleMap.h.
Member Function Documentation
TempMapIterator HepMC::TempParticleMap::begin () [inline]
Definition at line 36 of file TempParticleMap.h.
TempMapIterator HepMC::TempParticleMap::end () [inline]
Definition at line 37 of file TempParticleMap.h.
Referenced by end_vertex().
orderIterator HepMC::TempParticleMap::order_begin () [inline]
Definition at line 38 of file TempParticleMap.h.
Referenced by HepMC::IO_ExtendedAscii::fill_next_event(), and HepMC::IO_Ascii::fill_next_event().
orderIterator HepMC::TempParticleMap::order_end () [inline]
Definition at line 39 of file TempParticleMap.h.
Referenced by HepMC::IO_ExtendedAscii::fill_next_event(), and HepMC::IO_Ascii::fill_next_event().
int HepMC::TempParticleMap::end_vertex (GenParticle *) [inline]
Definition at line 51 of file TempParticleMap.h.
References end(), and p.
Referenced by HepMC::IO_ExtendedAscii::fill_next_event(), and HepMC::IO_Ascii::fill_next_event().
void HepMC::TempParticleMap::addEndParticle (GenParticle *, int &) [inline]
Definition at line 59 of file TempParticleMap.h.
References p.
Referenced by HepMC::IO_ExtendedAscii::read_particle(), and HepMC::IO_Ascii::read_particle().
The documentation for this class was generated from the following file:
TempParticleMap.h