example_ReadPDGtable.cc File Reference
#include `HepMC/IO_PDG_ParticleDataTable.h`
Functions
int main ()
Function Documentation
int main ()
Definition at line 16 of file example_ReadPDGtable.cc.
References HepMC::IO_PDG_ParticleDataTable::add_quarks_to_table(), HepMC::ParticleDataTable::delete_all(), HepMC::ParticleDataTable::make_antiparticles_from_particles(), HepMC::ParticleDataTable::print(), HepMC::IO_PDG_ParticleDataTable::rdstate(), and HepMC::IO_BaseClass::read_particle_data_table().