example_MyHerwig.cc File Reference
#include <iostream>
#include `HepMC/HerwigWrapper.h`
#include `HepMC/IO_HERWIG.h`
#include `HepMC/GenEvent.h`
#include `HepMC/HEPEVT_Wrapper.h`
Functions
int main ()
Function Documentation
int main ()
To Compile: go to the HepMC directory and type: gmake examples/example_MyHerwig.exe
In this example the precision and number of entries for the HEPEVT fortran common block are explicitly defined to correspond to those used in the Herwig version of the HEPEVT common block. If you get funny output from HEPEVT in your own code, probably you have set these values incorrectly!
Definition at line 23 of file example_MyHerwig.cc.
References hwbgen, hwbmch, hwcdec, hwcfor, hwdhad, hwdhob, hwdhvy, hwefin, hweini, hwepro, hwevnt, hwigin, hwmevt, hwproc, hwufne, hwuinc, hwuine, HepMC::GenEvent::print(), HepMC::HEPEVT_Wrapper::print_hepevt(), HepMC::IO_BaseClass::read_next_event(), HepMC::GenEvent::set_event_number(), HepMC::HEPEVT_Wrapper::set_max_number_entries(), HepMC::GenEvent::set_signal_process_id(), and HepMC::HEPEVT_Wrapper::set_sizeof_real().