example_BuildEventFromScratch.cc File Reference
#include <iostream>
#include `VectorConversion.h`
#include `HepMC/GenEvent.h`
#include `HepMC/ParticleDataTable.h`
#include `CLHEP/Vector/LorentzVector.h`
Namespaces
namespace CLHEP
Functions
int main ()
Function Documentation
int main ()
Examples:
example_BuildEventFromScratch.cc, example_EventSelection.cc, example_MyHerwig.cc, example_MyPythia.cc, example_MyPythiaOnlyToHepMC.cc, example_MyPythiaRead.cc, example_MyPythiaWithEventSelection.cc, example_PythiaParticle.cc, and example_UsingIterators.cc.
Definition at line 26 of file example_BuildEventFromScratch.cc.
References HepMC::GenVertex::add_particle_in(), HepMC::GenVertex::add_particle_out(), HepMC::GenEvent::add_vertex(), HepMC::clifetime_from_width(), HepMC::ParticleDataTable::delete_all(), HepMC::ParticleDataTable::insert(), p, HepMC::GenEvent::particles_begin(), HepMC::GenEvent::particles_end(), HepMC::GenEvent::print(), HepMC::ParticleDataTable::print(), HepMC::GenEvent::set_signal_process_vertex(), and SVtoLV().