example_MyPythiaRead.cc File Reference
#include <iostream>
#include `HepMC/PythiaWrapper.h`
#include `HepMC/IO_HEPEVT.h`
#include `HepMC/IO_Ascii.h`
#include `HepMC/GenEvent.h`
#include `PythiaHelper.h`
Functions
int main ()
Function Documentation
int main ()
Definition at line 28 of file example_MyPythiaRead.cc.
References HepMC::GenEvent::event_number(), initPythia(), HepMC::IO_BaseClass::read_next_event(), HepMC::GenEvent::set_event_number(), HepMC::HEPEVT_Wrapper::set_max_number_entries(), HepMC::GenEvent::set_signal_process_id(), and HepMC::HEPEVT_Wrapper::set_sizeof_real().