example_MyPythiaOnlyToHepMC.cc File Reference
#include <iostream>
#include `HepMC/PythiaWrapper.h`
#include `HepMC/IO_HEPEVT.h`
#include `HepMC/GenEvent.h`
#include `PythiaHelper.h`
Functions
int main ()
Function Documentation
int main ()
Definition at line 23 of file example_MyPythiaOnlyToHepMC.cc.
References initPythia(), pypars, HepMC::IO_BaseClass::read_next_event(), HepMC::HEPEVT_Wrapper::set_max_number_entries(), HepMC::GenEvent::set_mpi(), and HepMC::HEPEVT_Wrapper::set_sizeof_real().