example_MyPythia.cc File Reference
#include <iostream>
#include `HepMC/PythiaWrapper.h`
#include `HepMC/IO_HEPEVT.h`
#include `HepMC/IO_Ascii.h`
#include `HepMC/IO_ExtendedAscii.h`
#include `HepMC/GenEvent.h`
#include `PythiaHelper.h`
Functions
int main ()
Function Documentation
int main ()
To Compile: go to the HepMC directory and type: gmake examples/example_MyPythia.exe
In this example the precision and number of entries for the HEPEVT fortran common block are explicitly defined to correspond to those used in the Pythia version of the HEPEVT common block.
If you get funny output from HEPEVT in your own code, probably you have set these values incorrectly!
Definition at line 29 of file example_MyPythia.cc.
References initPythia(), pypars, HepMC::IO_BaseClass::read_next_event(), HepMC::GenEvent::set_event_number(), HepMC::HEPEVT_Wrapper::set_max_number_entries(), HepMC::GenEvent::set_mpi(), HepMC::GenEvent::set_signal_process_id(), and HepMC::HEPEVT_Wrapper::set_sizeof_real().