example_UsingIterators.cc File Reference
#include `HepMC/IO_Ascii.h`
#include `HepMC/GenEvent.h`
#include <math.h>
#include <algorithm>
#include <list>
Classes
class IsPhoton
example class
class IsW_Boson
example class
class IsFinalState
example class
Functions
int main ()
Function Documentation
int main ()
Definition at line 56 of file example_UsingIterators.cc.
References HepMC::copy_if(), HepMC::descendants, p, HepMC::parents, HepMC::GenEvent::particles_begin(), HepMC::GenEvent::particles_end(), HepMC::IO_Ascii::rdstate(), HepMC::IO_BaseClass::read_next_event(), v, HepMC::GenEvent::vertices_begin(), and HepMC::GenEvent::vertices_end().