HepMC Namespace Reference
Classes
class Flow
The flow object.
class GenEvent
The GenEvent class is the core of HepMC.
class GenParticle
The GenParticle class contains information about generated particles.
class GenVertex
GenVertex contains information about decay vertices.
class HeavyIon
The HeavyIon class stores information about heavy ions.
class HEPEVT_Wrapper
Generic Wrapper for the fortran HEPEVT common block.
class IO_Ascii
IO_Ascii is used to read or write from an ascii file.
class IO_AsciiParticles
event input/output in ascii format for eye and machine reading
class IO_BaseClass
all input/output classes inherit from IO_BaseClass
class IO_ExtendedAscii
IO_ExtendedAscii also deals with HeavyIon and PdfInfo.
class IO_HEPEVT
HEPEVT IO class.
class IO_HERWIG
IO_HERWIG is used to get Herwig information.
class IO_PDG_ParticleDataTable
an example ParticleDataTable IO method
class ParticleData
an example ParticleData class
class ParticleDataTable
an example ParticleDataTable class
class PdfInfo
The PdfInfo class stores PDF information.
class Polarization
The Polarization class stores theta and phi for a GenParticle.
class FourVector
FourVector is a simple representation of a physics 4 vector.
class ThreeVector
ThreeVector is a simple representation of a position or displacement 3 vector.
class TempParticleMap
TempParticleMap is a temporary GenParticle* container used during input.
class WeightContainer
Container for the Weights associated with an event or vertex.
Namespaces
namespace detail
Enumerations
enum IteratorRange {
parents,
children,
family,
ancestors,
descendants,
relatives
 }
type of iteration
Functions
template<class InputIterator, class OutputIterator, class Predicate> void copy_if (InputIterator first, InputIterator last, OutputIterator out, Predicate pred)
define the type of iterator to use
double clifetime_from_width (double width)
set lifetime from width
bool not_in_vector (std::vector< HepMC::GenParticle * > *, GenParticle *)
returns true if it cannot find GenParticle* in the vector
std::vector< HepMC::GenParticle * >::iterator already_in_vector (std::vector< HepMC::GenParticle * > *, GenParticle *)
void version ()
print HepMC version
void writeVersion (std::ostream &os)
write HepMC version to os
std::string versionName ()
return HepMC version
std::ostream & operator<< (std::ostream &ostr, const Flow &f)
for printing
std::ostream & operator<< (std::ostream &ostr, const GenParticle &part)
print particle
std::ostream & operator<< (std::ostream &ostr, const GenVertex &vtx)
print vertex information
std::ostream & operator<< (std::ostream &ostr, const ParticleData &pdata)
write to ostr
std::ostream & operator<< (std::ostream &ostr, const Polarization &polar)
print polarization information
bool not_in_vector (std::vector< GenParticle * > *v, GenParticle *p)
std::vector< HepMC::GenParticle * >::iterator already_in_vector (std::vector< GenParticle * > *v, GenParticle *p)
returns true if GenParticle is in the vector
Variables
static const double HepMC_hbarc
hbar * c --> calculated with units of [mm*GeV]
static const double HepMC_pi = 3.14159265358979323846
Detailed Description
All classes in the HepMC packages are in the HepMC namespace
Enumeration Type Documentation
enum HepMC::IteratorRange
type of iteration
Enumerator:
parents
children
family
ancestors
descendants
relatives
Definition at line 35 of file GenVertex.h.
Function Documentation
std::vector<HepMC::GenParticle*>::iterator HepMC::already_in_vector (std::vector< GenParticle * > * v, GenParticle * p)
returns true if GenParticle is in the vector
Definition at line 18 of file SearchVector.cc.
References p.
std::vector<HepMC::GenParticle*>::iterator HepMC::already_in_vector (std::vector< HepMC::GenParticle * > *, GenParticle *)
Returns the index of a GenParticle* within a vector. Returns -1 if GenParticle* is not in the vector.
Referenced by not_in_vector(), HepMC::GenVertex::remove_particle_in(), and HepMC::GenVertex::remove_particle_out().
double HepMC::clifetime_from_width (double width)
set lifetime from width
if you want to instantiate the particle lifetime from its width, use this static method inside the constructor:
Examples:
example_BuildEventFromScratch.cc.
Definition at line 110 of file ParticleData.cc.
References HepMC_hbarc.
Referenced by main(), and HepMC::IO_PDG_ParticleDataTable::read_entry().
template<class InputIterator, class OutputIterator, class Predicate> void HepMC::copy_if (InputIterator first, InputIterator last, OutputIterator out, Predicate pred) [inline]
define the type of iterator to use
Examples:
example_UsingIterators.cc.
Definition at line 50 of file GenEvent.h.
Referenced by main().
bool HepMC::not_in_vector (std::vector< GenParticle * > * v, GenParticle * p)
Definition at line 11 of file SearchVector.cc.
References already_in_vector(), and p.
bool HepMC::not_in_vector (std::vector< HepMC::GenParticle * > *, GenParticle *)
returns true if it cannot find GenParticle* in the vector
std::ostream& HepMC::operator<< (std::ostream & ostr, const Polarization & polar)
print polarization information
Definition at line 107 of file Polarization.cc.
References HepMC::Polarization::phi(), and HepMC::Polarization::theta().
std::ostream& HepMC::operator<< (std::ostream & ostr, const ParticleData & pdata)
write to ostr
Definition at line 94 of file ParticleData.cc.
References HepMC::ParticleData::charge(), HepMC::ParticleData::clifetime(), HepMC::ParticleData::mass(), HepMC::ParticleData::name(), HepMC::ParticleData::pdg_id(), and HepMC::ParticleData::spin().
std::ostream& HepMC::operator<< (std::ostream & ostr, const GenVertex & vtx)
print vertex information
Definition at line 429 of file GenVertex.cc.
References HepMC::GenVertex::barcode(), HepMC::GenVertex::position(), and HepMC::FourVector::x().
std::ostream& HepMC::operator<< (std::ostream & ostr, const GenParticle & part)
print particle
Definition at line 195 of file GenParticle.cc.
References HepMC::GenVertex::barcode(), HepMC::GenParticle::barcode(), HepMC::FourVector::e(), HepMC::GenParticle::end_vertex(), HepMC::GenParticle::momentum(), HepMC::GenParticle::pdg_id(), HepMC::FourVector::px(), HepMC::FourVector::py(), HepMC::FourVector::pz(), and HepMC::GenParticle::status().
std::ostream& HepMC::operator<< (std::ostream & ostr, const Flow & f)
for printing
Definition at line 190 of file Flow.cc.
References HepMC::Flow::m_icode.
void HepMC::version () [inline]
print HepMC version
Definition at line 26 of file Version.h.
References versionName().
std::string HepMC::versionName () [inline]
return HepMC version
Definition at line 21 of file Version.h.
Referenced by version(), HepMC::IO_ExtendedAscii::write_event(), HepMC::IO_AsciiParticles::write_event(), HepMC::IO_Ascii::write_event(), and writeVersion().
void HepMC::writeVersion (std::ostream & os) [inline]
write HepMC version to os
Definition at line 32 of file Version.h.
References versionName().
Referenced by HepMC::GenEvent::print_version().
Variable Documentation
const double HepMC::HepMC_hbarc [static]
Initial value:
 (6.6260755e-34 * (1.e-6/1.60217733e-19) / (2*3.14159265358979323846))
                                        * (2.99792458e+8 * 1000.) * 1.e+3
hbar * c --> calculated with units of [mm*GeV]
Definition at line 56 of file ParticleData.h.
Referenced by clifetime_from_width(), HepMC::ParticleData::set_width(), and HepMC::ParticleData::width().
const double HepMC::HepMC_pi = 3.14159265358979323846 [static]
Definition at line 19 of file Polarization.h.