testSimpleVector.cc File Reference
#include <iostream>
#include `HepMC/SimpleVector.h`
Functions
int main ()
Function Documentation
int main ()
Definition at line 8 of file testSimpleVector.cc.
References HepMC::FourVector::eta(), HepMC::FourVector::m(), HepMC::FourVector::m2(), HepMC::ThreeVector::mag(), HepMC::ThreeVector::perp(), HepMC::ThreeVector::perp2(), HepMC::ThreeVector::phi(), HepMC::FourVector::pseudoRapidity(), HepMC::ThreeVector::r(), HepMC::FourVector::set(), HepMC::ThreeVector::set(), HepMC::FourVector::setE(), HepMC::ThreeVector::setPhi(), HepMC::FourVector::setPx(), HepMC::FourVector::setPy(), HepMC::FourVector::setPz(), HepMC::FourVector::setT(), HepMC::ThreeVector::setTheta(), HepMC::FourVector::setX(), HepMC::ThreeVector::setX(), HepMC::FourVector::setY(), HepMC::ThreeVector::setY(), HepMC::FourVector::setZ(), HepMC::ThreeVector::setZ(), HepMC::FourVector::t(), HepMC::ThreeVector::theta(), v, HepMC::FourVector::x(), HepMC::ThreeVector::x(), HepMC::FourVector::y(), HepMC::ThreeVector::y(), HepMC::FourVector::z(), and HepMC::ThreeVector::z().