testPrintBug.cc File Reference
#include <fstream>
#include `HepMC/GenEvent.h`
#include `HepMC/SimpleVector.h`
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 10 of file testPrintBug.cc.
References HepMC::GenVertex::add_particle_in(), HepMC::GenVertex::add_particle_out(), HepMC::GenEvent::add_vertex(), and HepMC::GenEvent::print().